language: python
python:
  - "3.6" 
env:
  - DATABASE_URL=sqlite:///db.sqlite3
cache:
  yarn: true
  pip: true
install:
  - pip install -r requirements.txt
  - yarn install
script:
  - python manage.py test --noinput
  - yarn test


# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: cmput404-socialdistribution