language: node_js
python:
- '3.6'
install:
- yarn install
script:
- yarn test
node_js:
- 13.6.0
cache: yarn
deploy:
  provider: heroku
  api_key:
    secure: e9TdX4OshSmEOrYsHTo1FspZyged82N38c5JUUZlRUj95FnOlxXBNqwccLUOvC4MOWcVKJifRosF1AaWnrhPu9vsm3iSGt49T3MRaMvHSN8P2Dz/dr2QD2drSFPqWdFCJKwT5NUOp7m+cWkyT2H+HgGOVMJFpXCUff9DIQ38QaQzW7PE4UZ2+ID2/2gQZc6y+h7DgdVPkU8y7RPRzKA2RTkdOjSfShhVCky1HF2zufLHhwq2X/2ia4yskFprRR3E+pDRI+yZNlEWwoOWcnIrlXc3VVcserMCJatnyUaOkaN7z8piZ7UEwVsvXYe7cdhzrKLG9P6nPT9tFuzzZWjzwdj0RUmEtSn8PYBv1UDhZt55xlqpYu91A5lpJADrFf8xGJve6I4N7TgJ82rKmU07m+cNchKtkVROfTIHflV5hS9YMbgkE/94VjzJjlM0iiDFJneCKgJgp52c/HeA9TYHk2KwykESmV3wpHx4iFzJJj9gvjdBG8MH6IKVUHxDdkkgqTRpq+zNiMri/6Gjbzcx3/BSH4XchXbzMhmDmK3iAGr0kUT51ev8xAuxBSAJi6kPZf503Yv9kFXAoKchWhJl7DuBJRXd7dpRp1QUzzp8Tjzx7I1k/wDk5O+KqMCzEThap2v3QBoLHgCHX8QYG3HGfS9kCDlt/0RRN64KtJq7LbU=
