language: python
python:
  - "3.6" 
cache:
  yarn: true
  pip: true
install:
  - pip install -r requirements.txt
  - yarn install
script:
  - python manage.py test --noinput
  - yarn test


# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: cmput404-socialdistribution

# Send notifications to Slack when a build occurs
notifications:
  slack: cmput404team2:X4ovyEEbhpnyz8PzuK0KYrIG