language: python
python:
  - "3.6" 
env:
  - DATABASE_URL=sqlite:///db.sqlite3
cache:
  yarn: true
  pip: true
install:
  - pip install -r requirements.txt
  - yarn install
script:
  - py.test backend/
  - yarn test


# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: cmput404-socialdistribution

# Send notification to Slack on deploy
notifications:
  slack: cmput404team2:X4ovyEEbhpnyz8PzuK0KYrIG 