language: python
python:
  - "3.6" 
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --noinput

language: node_js
python:
- '3.6'
install:
- yarn install
script:
- yarn test
node_js:
- 13.6.0
cache: yarn

# Deploy to Heroku
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
