language: python
python:
  - "3.6" 
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --noinput

language: node_js
node_js: node
cache: yarn
install:
  - yarn install
script:
  - yarn test