# Generated by Django 3.0.2 on 2020-03-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200304_0421'),
        ('backend', '0007_post_visibleto'),
    ]

    operations = [
    ]
