# Generated by Django 3.0.2 on 2020-03-04 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200304_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_fromUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_toUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
