# Generated by Django 3.0.2 on 2020-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_fullid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('text/markdown', 'text/markdown'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain', max_length=30),
        ),
    ]
