# Generated by Django 3.0.2 on 2020-03-10 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_comments_postedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
