# Generated by Django 3.0.2 on 2020-03-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_comments_contenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
