# Generated by Django 3.0.2 on 2020-04-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
